TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
# DB += dbExample1.db
# DB += dbExample2.db
# DB += dbSubExample.db
DB += libcom1.db
DB += libcom1.proto
DB += pressure.db
DB += interlockbox.db
DB += sensorbox.db
DB += solenoidbox.db
DB += matsusada_au20p7.db
DB += matsusada_co_ctrl.proto
DB += rek.db
DB += rek.proto
DB += tdk.db
DB += tdk.proto
DB += thermocouples.db
DB += aim.db
DB += aim.proto
DB += user.substitutions

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

